import { useState, useRef } from 'react';
import { toPng } from 'html-to-image';
import { toast } from 'sonner';
import jsPDF from "jspdf";
import { FileText, Download, Shield, Camera, Lock, ChevronDown } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';

const EvidenceCardDisplay = ({ url, timestamp, hash }: { url: string, timestamp: string, hash: string }) => (
  <div className="bg-slate-950 border-2 border-slate-800 p-6 rounded-lg shadow-2xl font-mono relative overflow-hidden text-white w-full max-w-md mx-auto">
    <div className="absolute inset-0 opacity-5 pointer-events-none flex items-center justify-center">
       <Shield size={200} />
    </div>
    <div className="flex justify-between items-start border-b border-slate-800 pb-4 mb-4 relative z-10">
      <div className="flex items-center gap-3">
        <div className="p-2 bg-green-500/10 rounded-full border border-green-500/50">
          <Lock className="w-5 h-5 text-green-500" />
        </div>
        <div>
          <h3 className="text-sm font-bold text-green-500 tracking-wider">VERIFIED CAPTURE</h3>
          <p className="text-[10px] text-slate-500">DIGITAL FORENSIC LOG</p>
        </div>
      </div>
      <div className="text-right">
        <h4 className="font-bold text-white tracking-widest">RIGHTSRADAR</h4>
        <p className="text-[10px] text-purple-400">NON-REPUDIATION PROOF</p>
      </div>
    </div>
    <div className="space-y-4 relative z-10 text-xs">
      <div className="space-y-1">
        <p className="text-slate-500 uppercase tracking-widest text-[10px]">Target URL</p>
        <p className="text-blue-400 break-all bg-blue-950/30 p-2 rounded border border-blue-900/50 font-medium">
          {url}
        </p>
      </div>
      <div className="grid grid-cols-2 gap-4">
        <div className="space-y-1">
           <p className="text-slate-500 uppercase tracking-widest text-[10px]">Timestamp (UTC)</p>
           <p className="text-orange-400 font-bold">{timestamp}</p>
        </div>
        <div className="space-y-1">
           <p className="text-slate-500 uppercase tracking-widest text-[10px]">Status</p>
           <p className="text-green-400">AUTHENTICATED</p>
        </div>
      </div>
      <div className="space-y-1">
        <p className="text-slate-500 uppercase tracking-widest text-[10px]">Cryptographic Hash (SHA-256)</p>
        <div className="bg-slate-900 p-2 rounded border border-slate-800 break-all text-[10px] text-slate-400">
          {hash}
        </div>
      </div>
    </div>
    <div className="mt-6 pt-4 border-t border-slate-800 flex justify-between items-center relative z-10">
       <p className="text-[9px] text-slate-600">ID: {Math.random().toString(36).substr(2, 9).toUpperCase()}</p>
       <p className="text-[9px] text-slate-600">GENERATED BY RIGHTSRADAR.ORG</p>
    </div>
  </div>
);

export default function AdvocacyReport() {
  const [url, setUrl] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [captureData, setCaptureData] = useState<{ url: string; timestamp: string; hash: string } | null>(null);
  const evidenceCardRef = useRef<HTMLDivElement>(null);
  const [selectedCountry, setSelectedCountry] = useState<string>("");

  const countries = ["Kenya", "Nigeria", "South Africa", "Uganda", "India", "Brazil", "United States", "United Kingdom"];

  const generateMockHash = async (url: string) => {
    await new Promise(resolve => setTimeout(resolve, 1500)); 
    const timestamp = new Date().toUTCString();
    const hash = `0x${[...Array(64)].map(() => Math.floor(Math.random() * 16).toString(16)).join('')}`;
    return { url, timestamp, hash };
  };

  const handleCapture = async () => {
    if (!url) {
      toast.error('Please enter a URL to capture.');
      return;
    }
    setIsLoading(true);
    setCaptureData(null);
    toast.loading('Hashing content... Verifying integrity...');
    try {
      const { url: capturedUrl, timestamp, hash } = await generateMockHash(url);
      setCaptureData({ url: capturedUrl, timestamp, hash });
      toast.success('Digital proof generated successfully!');
    } catch (error) {
      toast.error('Failed to generate proof. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleDownloadPNG = () => {
    if (!evidenceCardRef.current) return;
    toast.loading('Downloading forensic image...');
    toPng(evidenceCardRef.current, { cacheBust: true, quality: 1.0, pixelRatio: 2 })
      .then((dataUrl) => {
        const link = document.createElement('a');
        link.download = `Evidence_Log_${Date.now()}.png`;
        link.href = dataUrl;
        link.click();
        toast.dismiss();
        toast.success('Evidence saved to device.');
      })
      .catch((err) => {
        console.error(err);
        toast.error('Download failed.');
      });
  };

  const handleGeneratePDF = () => {
    if (!selectedCountry) {
        toast.error("Please select a country first.");
        return;
    }

    toast.loading(`Generating Official Report for ${selectedCountry}...`);
    const doc = new jsPDF();
    
    doc.setFillColor(15, 23, 42); 
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("RIGHTSRADAR OFFICIAL REPORT", 105, 20, { align: "center" });
    doc.setFontSize(10);
    doc.text("SUBMISSION TO THE UNITED NATIONS HUMAN RIGHTS COUNCIL", 105, 30, { align: "center" });

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(`SUBJECT: Digital Safety Gap Analysis - ${selectedCountry.toUpperCase()}`, 20, 60);
    doc.text(`DATE: ${new Date().toLocaleDateString()}`, 20, 70);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    const summary = `This document serves as formal evidence regarding critical gaps in digital safety legislation in ${selectedCountry}. ` +
      "Our automated tracking systems have identified specific failures in protecting women from " +
      "Online Gender-Based Violence (OGBV). Immediate legislative action is recommended.";
    doc.text(summary, 20, 90, { maxWidth: 170, lineHeightFactor: 1.5 });

    doc.setDrawColor(220, 38, 38); 
    doc.setLineWidth(1);
    doc.rect(20, 140, 170, 30);
    doc.setTextColor(220, 38, 38);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("STATUS: CRITICAL ACTION REQUIRED", 105, 160, { align: "center" });

    doc.save(`RightsRadar_${selectedCountry}_Report.pdf`);
    toast.dismiss();
    toast.success('Official PDF Report Downloaded');
  };

  return (
    <div className="container mx-auto px-4 py-12 text-white">
      <div className="text-center mb-12 space-y-4">
        <h1 className="text-4xl md:text-5xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-purple-400 to-pink-600">
          Advocacy & Evidence Toolkit
        </h1>
        <p className="text-gray-400 max-w-2xl mx-auto text-lg">
          Equipping activists with professional tools to document harm and demand accountability.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        
        <Card className="bg-gray-900 border-purple-500/30 shadow-lg">
          <CardHeader>
            <div className="flex items-center gap-3 mb-2">
              <div className="p-2 bg-purple-500/20 rounded-lg">
                <FileText className="h-6 w-6 text-purple-400" />
              </div>
              <CardTitle className="text-2xl text-white">The Geneva Generator</CardTitle>
            </div>
            <CardDescription className="text-gray-400">
              Turn data into diplomacy. Generate a formal UN Human Rights complaint PDF with one click.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="p-6 bg-black/40 rounded-lg border border-gray-800 flex flex-col items-center text-center space-y-4">
              <Shield className="h-16 w-16 text-gray-700" />
              <p className="text-sm text-gray-500">
                Select a country to auto-populate the legal framework analysis.
              </p>
              
              <div className="w-full relative">
                <select 
                    value={selectedCountry}
                    onChange={(e) => setSelectedCountry(e.target.value)}
                    className="w-full bg-gray-800 border border-gray-700 text-white rounded-md px-4 py-3 appearance-none focus:ring-2 focus:ring-purple-500 focus:outline-none cursor-pointer"
                >
                    <option value="" disabled>Select Target Country</option>
                    {countries.map(c => <option key={c} value={c}>{c}</option>)}
                </select>
                <ChevronDown className="absolute right-3 top-3.5 h-5 w-5 text-gray-500 pointer-events-none" />
              </div>
            </div>

            <Button 
              onClick={handleGeneratePDF}
              className="w-full h-14 text-lg font-bold bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700 disabled:opacity-50 disabled:cursor-not-allowed"
              disabled={!selectedCountry}
            >
              <Download className="mr-2 h-5 w-5" /> Download Official PDF
            </Button>
          </CardContent>
        </Card>

        <Card className="bg-gray-900 border-blue-500/30 shadow-lg">
          <CardHeader>
             <div className="flex items-center gap-3 mb-2">
              <div className="p-2 bg-blue-500/20 rounded-lg">
                <Camera className="h-6 w-6 text-blue-400" />
              </div>
              <CardTitle className="text-2xl text-white">Digital Notary</CardTitle>
            </div>
            <CardDescription className="text-gray-400">
              Create a timestamped, cryptographically hashed snapshot of online harassment for legal proof.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="flex gap-2">
              <Input
                type="url"
                placeholder="Paste URL of harmful content..."
                value={url}
                onChange={(e) => setUrl(e.target.value)}
                disabled={isLoading}
                className="bg-gray-800 border-gray-700 text-white"
              />
              <Button onClick={handleCapture} disabled={isLoading} className="bg-blue-600 hover:bg-blue-700">
                {isLoading ? 'Hashing...' : 'Capture'}
              </Button>
            </div>

            <div className="bg-black/40 rounded-lg border border-gray-800 min-h-[300px] flex items-center justify-center p-4">
              {!captureData && !isLoading && (
                <div className="text-center text-gray-600">
                  <Lock className="h-12 w-12 mx-auto mb-2 opacity-20" />
                  <p className="text-sm">Secure Evidence Locker Empty</p>
                </div>
              )}
              {isLoading && (
                 <div className="text-center text-blue-400 animate-pulse">
                    <p>Generating cryptographic hash...</p>
                 </div>
              )}
              {captureData && (
                <div className="w-full">
                   <div ref={evidenceCardRef}>
                      <EvidenceCardDisplay 
                        url={captureData.url}
                        timestamp={captureData.timestamp}
                        hash={captureData.hash} 
                      />
                   </div>
                   <Button onClick={handleDownloadPNG} className="w-full mt-4 bg-orange-600 hover:bg-orange-700">
                      <Download className="mr-2 h-4 w-4" /> Save Evidence (PNG)
                   </Button>
                </div>
              )}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}